/*
 * generated by Xtext 2.10.0
 */
package eu.metatools.util.featurelogic.term


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TermRuntimeModule extends AbstractTermRuntimeModule {
}
