/*
 * generated by Xtext 2.10.0
 */
package eu.metatools.util.featurelogic.term


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TermStandaloneSetup extends TermStandaloneSetupGenerated {

	def static void doSetup() {
		new TermStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
